[project]
name = "process"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "matplotlib>=3.10.8",
    "notebook>=7.5.1",
    "opencv-python>=4.12.0.88",
]
